#spring.application.name=user-service

server:
  port: 8090

spring:
  application:
    name : user-service
  datasource:
    url: jdbc:postgresql://localhost:1234/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: ui5zz55TVMCMVZoCW9rU9gEdG6wMtMo8Xf0MP7Zoa0k=
  expiration: 86400000
