server:
  port: 8082

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://postgres-order-db:5432/order_db
    username: postgres
    password: my-secret-pw
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: kafka:9092

  security:
    oauth2:
      resource-server:
        jwt:
          secret-key: ui5zz55TVMCMVZoCW9rU9gEdG6wMtMo8Xf0MP7Zoa0k=

service:
  product:
    url: http://product-service:8081
  user:
    url: http://user-service:8090
